
services:
  postgres:
    image: postgres:latest
    container_name: db_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge