
services:
  postgres:
    image: postgres:latest
    container_name: db_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./customer:/customer:ro
      - ./import_csv.sh:/import_csv.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge