#!/bin/bash
set -e

CSV_FILE="/customer/$1"
TABLE_NAME=$(basename "$1" .csv)

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE TABLE IF NOT EXISTS $TABLE_NAME();
    TRUNCATE TABLE $TABLE_NAME;
    COPY $TABLE_NAME FROM '$CSV_FILE' DELIMITER ',' CSV HEADER;
EOSQL